"""Source adapters — one `adapt()` + manifests. No per-provider adapter modules."""

from joel.adapters.base import (
    SourceManifest,
    TriageReport,
    adapt,
    adapt_many,
    group_threads,
    triage,
    triage_batch,
)
from joel.adapters.manifests import (
    GITHUB_ISSUE,
    GITHUB_ISSUE_COMMENT,
    GITHUB_PR,
    GITHUB_PR_REVIEW,
    GITHUB_CODE,
    GMAIL,
    LINEAR_ISSUE,
    JIRA_ISSUE,
    NOTION_PAGE,
    CONFLUENCE_PAGE,
    GDRIVE_FILE,
    HUBSPOT_DEAL,
    FIREFLIES_CHUNK,
    SLACK,
)

__all__ = [
    "SourceManifest",
    "TriageReport",
    "adapt",
    "adapt_many",
    "group_threads",
    "triage",
    "triage_batch",
    "SLACK",
    "GITHUB_ISSUE",
    "GITHUB_ISSUE_COMMENT",
    "GITHUB_PR",
    "GITHUB_PR_REVIEW",
    "GITHUB_CODE",
    "GMAIL",
    "LINEAR_ISSUE",
    "JIRA_ISSUE",
    "NOTION_PAGE",
    "CONFLUENCE_PAGE",
    "GDRIVE_FILE",
    "HUBSPOT_DEAL",
    "FIREFLIES_CHUNK",
]
